### ISSUE TITLE
[suggestion] add api and recommended flags 

### ISSUE THREAD

**Issue by BlackRandomCraft** [encode42/flags.sh#26]
Well, I think it's clear with the api, but with the recommended flags I would think about it
```
java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dspt={{{SERVER_PORT}}} -XX:+UseSerialGC -Dlog4j2.formatMsgNoLookups=true -Dfml.queryResult=confirm -Dterminal.jline=false -Dterminal.ansi=true -DIReallyKnowWhatIAmDoingISwear=true -Duser.timezone=Europe/Moscow -jar -Dfile.encoding=UTF-8 {{{SERVER_JARFILE}}} nogui
```
Such as these flags

**Comment by encode42** [comment]
An API is already implemented in the qwik rewrite! (#5)

I'm not sure what you mean by "recommended flags". The ones you provided are exclusive to certain platforms or environments, e.g. Pterodactyl or Forge. It wouldn't be a good idea to include them in configurations they're not designed for.
