### ISSUE TITLE
AutoRestart timer

### ISSUE THREAD

**Issue by playgamesgo** [encode42/flags.sh#3]
Change autorestart from
`    echo Server restarting...
    echo Press CTRL + C to stop.
done`
to
`for i in 3 2 1; do
        printf 'Server restarting in %s... (press CTRL-C to exit)\n' "${i}"
        sleep 1
    done
done`
This is useful not to spam Ctrl+C to shut down the server, but to have a time of 3 seconds to do it

**Comment by encode42** [comment]
This isn't needed IMO. You don't have to spam CTRL+C, just press it when it says the server is restarting.
