### ISSUE TITLE
VERSION 1.21 MUST BE SUPPORTED!

### ISSUE THREAD

**Issue by mkaksoy** [encode42/flags.sh#30]
When I try to open a server with 1.21, it gives a warning and the server does not load!

**Comment by encode42** [comment]
What warning? What environment? What selected options? The more information you provide, the more likely I can help.

Is it related to the Java class version? Keep in mind, that Minecraft 1.21 requires Java 21 to be installed and used.

Also, GitHub issues are for reporting bugs, while the Discord server is for support requests like this. You can still respond here! But for future reference, Discord is a better place for questions like these.
