### ISSUE TITLE
Suggestion to add a copy function function for prism's custom java arguments.

### ISSUE THREAD

**Issue by Today20092** [encode42/flags.sh#31]
When copying and pasting the java version there are some options that cannot go in here such as
```
java -Xms12288M -Xmx12288M 
```
and

```
-jar server.jar --nogui
```
![image](https://github.com/encode42/flags.sh/assets/79241611/79194e45-ee12-41a9-ad6a-190741acc60d)

**Comment by encode42** [comment]
This website is designed only for servers. Client-specific flags might be looked into in the future, but is currently not planned.

**Comment by encode42** [comment]
P.S. **do not** use server flags on the client! You'll very likely encounter issues and worse performance. The default flags do great.

**Comment by Today20092** [comment]
> P.S. **do not** use server flags on the client! You'll very likely encounter issues and worse performance. The default flags do great.

Thank you for this, did not know that.
