### ISSUE TITLE
[Inquiry] Project Status

### ISSUE THREAD

**Issue by TH3N3WN00B** [encode42/flags.sh#33]
Is this project still planed for an update or has this been abandoned all together?

**Comment by encode42** [comment]
Unknown

**Comment by encode42** [comment]
(additional information: this is a project that doesn't really need updating. the Java ecosystem is starting to move away from requiring flags at all. any future updates to this project will bear a complete change in focus.)

**Comment by TH3N3WN00B** [comment]
> (additional information: this is a project that doesn't really need updating. the Java ecosystem is starting to move away from requiring flags at all. any future updates to this project will bear a complete change in focus.)

Are you able to provide more information about this?

**Comment by encode42** [comment]
https://noflags.sh/about/
